### ISSUE TITLE
Question: On how to get the project running locally

### ISSUE THREAD

**Issue by cnohall** [nathan-gon/allcoin#2]
I ran `npm install` in the `client` folder, and then `npm start`. But it gives me this error:  

![image](https://user-images.githubusercontent.com/36883813/183336283-3289691e-6b21-4fe9-9aa3-dfedff4d0ce0.png)

Will probably look into it a bit more when I have time.

**Comment by nathan-gon** [comment]
I think you can install chart.js too 
can you try this please?
npm install --save chart.js react-chartjs-2

**Comment by cnohall** [comment]
Nice, that made it work. Strange that it didn't work by just running `npm install`. Thanks for the help!
